// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAxY5kXgcnYY0id8x-XrylUn4nKA23g34',
    appId: '1:155065374789:web:20e480ef5bbe13a5aa2b2c',
    messagingSenderId: '155065374789',
    projectId: 'grocerie-app-c70bd',
    authDomain: 'grocerie-app-c70bd.firebaseapp.com',
    storageBucket: 'grocerie-app-c70bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVt_b3j3QanH7gJHzcxlsfLb5o_rYx0Y',
    appId: '1:155065374789:android:28dbf2d0fe384141aa2b2c',
    messagingSenderId: '155065374789',
    projectId: 'grocerie-app-c70bd',
    storageBucket: 'grocerie-app-c70bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Ps_KP-rwQq12TlJcKhc8VekV-PbM1vY',
    appId: '1:155065374789:ios:1fb167f78fb6e64caa2b2c',
    messagingSenderId: '155065374789',
    projectId: 'grocerie-app-c70bd',
    storageBucket: 'grocerie-app-c70bd.firebasestorage.app',
    iosBundleId: 'rifqi.com.tubesMotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Ps_KP-rwQq12TlJcKhc8VekV-PbM1vY',
    appId: '1:155065374789:ios:1fb167f78fb6e64caa2b2c',
    messagingSenderId: '155065374789',
    projectId: 'grocerie-app-c70bd',
    storageBucket: 'grocerie-app-c70bd.firebasestorage.app',
    iosBundleId: 'rifqi.com.tubesMotion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAxY5kXgcnYY0id8x-XrylUn4nKA23g34',
    appId: '1:155065374789:web:a46cba9dc1775713aa2b2c',
    messagingSenderId: '155065374789',
    projectId: 'grocerie-app-c70bd',
    authDomain: 'grocerie-app-c70bd.firebaseapp.com',
    storageBucket: 'grocerie-app-c70bd.firebasestorage.app',
  );

}